apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: test-deployments 
spec: 
 replicas: 2
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: Pfe-test-back 
 template: 
   metadata: 
    labels: 
     app: Pfe-test-back
     env: prod 
   spec: 
    containers: 
    - name: test-container 
      image: souhaibhsoumi/backendproject:1
