apiVersion: v1
kind: Service
metadata:
 name: test-products
spec:
 type: NodePort
 selector:
   app: Pfe-test-back
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 85
   targetPort: 85
   nodePort: 32221
